# Usamos una imagen oficial de Python ligera
FROM python:3.9-slim

# Instalamos:
# 1. apache-beam: El framework base
# 2. kafka-python: Para leer de Kafka sin complicaciones de Java
# 3. pymongo: Para guardar los KPIs en la base de datos (NUEVO)
RUN pip install --no-cache-dir apache-beam[gcp] kafka-python pymongo

# Creamos directorio de trabajo
WORKDIR /app

# El contenedor se quedará esperando
CMD ["tail", "-f", "/dev/null"]